### ISSUE TITLE
Tap post to go into the post.

### ISSUE THREAD

**Issue by unoukujou** [kaangiray26/geddit-app#35] opened 2023-07-25 12:08 UTC
Instead of the arrow button at the bottom, just tap anywhere on the post to go into it. At the very least, be able to tap the post title to go into it.

**Comment by kaangiray26** [comment] 2023-07-25 12:10
Hi, can you please specify which version you are talking about?

**Comment by kaangiray26** [comment] 2023-07-25 12:11
Because in v1.6 you can directly go to the post when you click on the image, gallery image, video, text etc.

**Comment by unoukujou** [comment] 2023-07-25 14:37
Very good. I'm on 1.5. I'll update 1.6 and see it.

**Comment by EmilBerbakov** [comment] 2023-07-25 16:59
I am on the most recent version (love the redesign, by the way!) and I can confirm that you can open up posts with images by clicking on the image. It appears that there's no way to open up a purely text post without clicking on the open button. I think it would be a nice qol update if you could click on either the title or the post's card to open the post, in full. That way, any type of post could have this convenience feature.

**Comment by kaangiray26** [comment] 2023-07-26 23:52
I've added a new commit that enables you to tap anywhere on the post except the buttons, username, media, subreddit to go into the post view. This will be included in the next release :)

**Comment by kaangiray26** [comment] 2023-07-27 23:21
The feature is now in the latest release.

**Closed by kaangiray26** 2023-07-27 23:21 UTC
